/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentinformationsystem;

/**
 *
 * @author HP Probook
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        setSize(660,440);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtn1 = new controls.JButtn();
        jButtn2 = new controls.JButtn();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        jButtn3 = new controls.JButtn();
        CLogin = new controls.JCombo();
        jLabel4 = new javax.swing.JLabel();
        jButtn4 = new controls.JButtn();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Student Mangemnt System");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(45, 11, 571, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 120, 131, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 170, 131, 29);

        txtUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        getContentPane().add(txtUser);
        txtUser.setBounds(210, 120, 160, 30);

        txtPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtPass);
        txtPass.setBounds(210, 170, 160, 30);

        jButtn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButtn3.setText("Go");
        jButtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtn3);
        jButtn3.setBounds(400, 230, 120, 30);

        CLogin.setBorder(null);
        CLogin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Teacher", "Student" }));
        getContentPane().add(CLogin);
        CLogin.setBounds(200, 230, 176, 30);

        jLabel4.setBackground(new java.awt.Color(255, 51, 102));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login As");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 230, 110, 29);

        jButtn4.setText("Exit");
        jButtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtn4);
        jButtn4.setBounds(10, 360, 100, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 11, 10, 0);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP Probook\\Documents\\Student Information System\\build\\classes\\student\\information\\system\\images\\bk3.jpg")); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 710, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void jButtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtn4ActionPerformed
System.exit(0);
    }//GEN-LAST:event_jButtn4ActionPerformed

    private void jButtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtn3ActionPerformed
  String User = txtUser.getText();
  String Pass = txtPass.getText();
  boolean login = db.go.login(User, Pass);
    boolean loginStudent = db.go.loginStudent(User, Pass);

  String Comboitems = CLogin.getSelectedItem().toString();
  if(Comboitems.equalsIgnoreCase("Teacher") && login){
  this.dispose();
  Tools.OpenForm(new frmTeacher());
  }else if(Comboitems.equalsIgnoreCase("Student") && loginStudent ){
 this.dispose();
  Tools.OpenForm(new frmStudent());
  }else{
  Tools.MBox("Password Or UserName is Not Correct Pleas Try Agin");
  }
        
    }//GEN-LAST:event_jButtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JCombo CLogin;
    private controls.JButtn jButtn1;
    private controls.JButtn jButtn2;
    private controls.JButtn jButtn3;
    private controls.JButtn jButtn4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
