/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentinformationsystem;

import Student.Teacher;
import java.text.SimpleDateFormat;
import java.util.Date;
import javafx.geometry.VPos;
import javafx.scene.layout.GridPane;

/**
 *
 * @author HP Probook
 */
public class frmTeacher extends javax.swing.JFrame {

    /**
     * Creates new form frmTeacher
     */
    public frmTeacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSName = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        txtStreet = new javax.swing.JTextField();
        txtPostCode = new javax.swing.JTextField();
        txtNati = new javax.swing.JTextField();
        txtold = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtEmai = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtClassNumber = new javax.swing.JTextField();
        txtClassName = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtNow = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableStudent = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        btnrNationality = new javax.swing.JRadioButton();
        btnrDate = new javax.swing.JRadioButton();
        btnrFName = new javax.swing.JRadioButton();
        btnrOld = new javax.swing.JRadioButton();
        btnrNumber = new javax.swing.JRadioButton();
        btnrPostCode = new javax.swing.JRadioButton();
        btnrStreet = new javax.swing.JRadioButton();
        btnrEmail = new javax.swing.JRadioButton();
        btnrCity = new javax.swing.JRadioButton();
        btnrNow = new javax.swing.JRadioButton();
        btnrSName = new javax.swing.JRadioButton();
        btnrClassNumber = new javax.swing.JRadioButton();
        btnrPhone = new javax.swing.JRadioButton();
        btnrCalssName = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new controls.JButtn();
        btnAdd = new controls.JButtn();
        btnUpdate = new controls.JButtn();
        btnDelete = new controls.JButtn();
        btnClear = new controls.JButtn();
        btnFind = new controls.JButtn();
        btnBack = new controls.JButtn();
        btngetAll = new controls.JButtn();
        btnBack1 = new controls.JButtn();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Teacher");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Street");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Eduction_Old");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Phone Number");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Class Number");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Second Name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("PostCode");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Student number");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Nationality");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Class Name");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Email Adddres");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("City:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("BirtheDate");

        txtSName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSNameActionPerformed(evt);
            }
        });

        txtFName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        txtStreet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        txtPostCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtNati.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtold.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtEmai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtClassNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtClassName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtNow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Eduction Now");

        JTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FName", " SName", "BirthDate", "City", "Street", "PostCode", "Nationality ", "Eduction_Now", "Eduction_Old", " Number", "Email", "Phone", "Class_Number", "Class Name"
            }
        ));
        JTableStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableStudent);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Search By:");

        btnrNationality.setBackground(new java.awt.Color(255, 255, 255));
        btnrNationality.setText("Nationality");

        btnrDate.setBackground(new java.awt.Color(255, 255, 255));
        btnrDate.setText("Date");

        btnrFName.setBackground(new java.awt.Color(255, 255, 255));
        btnrFName.setSelected(true);
        btnrFName.setText("First Name");

        btnrOld.setBackground(new java.awt.Color(255, 255, 255));
        btnrOld.setText("Edu_Old");

        btnrNumber.setBackground(new java.awt.Color(255, 255, 255));
        btnrNumber.setText("StudentNumber");

        btnrPostCode.setBackground(new java.awt.Color(255, 255, 255));
        btnrPostCode.setText("PostCode");

        btnrStreet.setBackground(new java.awt.Color(255, 255, 255));
        btnrStreet.setText("Street");

        btnrEmail.setBackground(new java.awt.Color(255, 255, 255));
        btnrEmail.setText("Email");

        btnrCity.setBackground(new java.awt.Color(255, 255, 255));
        btnrCity.setText("City");

        btnrNow.setBackground(new java.awt.Color(255, 255, 255));
        btnrNow.setText("Edu_Now");

        btnrSName.setBackground(new java.awt.Color(255, 255, 255));
        btnrSName.setText("Second Name");
        btnrSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrSNameActionPerformed(evt);
            }
        });

        btnrClassNumber.setBackground(new java.awt.Color(255, 255, 255));
        btnrClassNumber.setText("Class Number");

        btnrPhone.setBackground(new java.awt.Color(255, 255, 255));
        btnrPhone.setText("Phone");

        btnrCalssName.setBackground(new java.awt.Color(255, 255, 255));
        btnrCalssName.setText("ClassName");

        txtSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btngetAll.setText("get All Rows");
        btngetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngetAllActionPerformed(evt);
            }
        });

        btnBack1.setText("Report");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addGap(72, 72, 72)
                        .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21)
                        .addComponent(txtold, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)
                        .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8)
                        .addGap(48, 48, 48)
                        .addComponent(txtPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9)
                        .addGap(10, 10, 10)
                        .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addComponent(txtClassNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14)
                        .addGap(26, 26, 26)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel10)
                        .addGap(41, 41, 41)
                        .addComponent(txtNati, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12)
                        .addGap(26, 26, 26)
                        .addComponent(txtEmai, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel11)
                        .addGap(43, 43, 43)
                        .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13)
                        .addGap(68, 68, 68)
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtNow, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16)
                        .addGap(36, 36, 36)
                        .addComponent(btnrFName)
                        .addGap(26, 26, 26)
                        .addComponent(btnrDate)
                        .addGap(18, 18, 18)
                        .addComponent(btnrStreet)
                        .addGap(10, 10, 10)
                        .addComponent(btnrPostCode)
                        .addGap(10, 10, 10)
                        .addComponent(btnrNationality)
                        .addGap(18, 18, 18)
                        .addComponent(btnrNow)
                        .addGap(10, 10, 10)
                        .addComponent(btnrOld)
                        .addGap(10, 10, 10)
                        .addComponent(btnrNumber)
                        .addGap(8, 8, 8)
                        .addComponent(btnrEmail)
                        .addGap(18, 18, 18)
                        .addComponent(btnrPhone)
                        .addGap(10, 10, 10)
                        .addComponent(btnrClassNumber)
                        .addGap(10, 10, 10)
                        .addComponent(btnrCalssName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnrSName)
                        .addGap(12, 12, 12)
                        .addComponent(btnrCity, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btngetAll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtClassNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtNati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtEmai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtNow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16))
                    .addComponent(btnrFName)
                    .addComponent(btnrDate)
                    .addComponent(btnrStreet)
                    .addComponent(btnrPostCode)
                    .addComponent(btnrNationality)
                    .addComponent(btnrNow)
                    .addComponent(btnrOld)
                    .addComponent(btnrNumber)
                    .addComponent(btnrEmail)
                    .addComponent(btnrPhone)
                    .addComponent(btnrClassNumber)
                    .addComponent(btnrCalssName))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnrSName)
                    .addComponent(btnrCity)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btngetAll, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSNameActionPerformed

    private void btnrSNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrSNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrSNameActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      Group.add(btnrFName);
     Group.add(btnrSName); 
       Group.add(btnrDate);
         Group.add(btnrCity);
           Group.add(btnrClassNumber);
             Group.add(btnrEmail);
             Group.add(btnrNow);
               Group.add(btnrOld);
                 Group.add(btnrPostCode);
                   Group.add(btnrStreet);
                     Group.add(btnrPhone);
                       Group.add(btnrNationality);
                         Group.add(btnrNumber);
                           Group.add(btnrCalssName);
btnAdd.setEnabled(true);
btnDelete.setEnabled(false);
btnUpdate.setEnabled(false);
t.getAllRows(JTableStudent);
txtNumber.setText(t.getAutoNumber());
JTableStudent.getTableHeader().setReorderingAllowed(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
this.dispose();
Tools.OpenForm(new frmLogin());
    }//GEN-LAST:event_btnBackActionPerformed
private void ClearAll(){
Tools.Clear(this);
txtFName.requestFocus();
txtNumber.setText(t.getAutoNumber());
t.getAllRows(JTableStudent);
}
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
ClearAll();// TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed
Teacher t = new Teacher();
private void SetValues(){
t.setFName(txtFName.getText());
t.setSName(txtSName.getText());
    SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
    String date = f.format(txtDate.getDate());
    t.setBirthDate(date);
    t.setCity(txtCity.getText());
    t.setStreet(txtStreet.getText());
    t.setPostCode(txtPostCode.getText());
t.setNationality(txtNati.getText());
t.setEduction_Now(txtNow.getText());
t.setEduction_Old(txtold.getText());
t.setStudent_Number(txtNumber.getText());
t.setEmail(txtEmai.getText());
t.setPhone(txtPhone.getText());
t.setClass_Numbe(txtClassNumber.getText());
t.setClaas_Name(txtClassName.getText());

}
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        SetValues();
        t.Add();
        ClearAll();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
       String Message = Tools.InputBox("Plese enter The Numer of Student");
       t.getOnseRow(Message, JTableStudent);
    }//GEN-LAST:event_btnFindActionPerformed

    private void btngetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngetAllActionPerformed
   t.getAllRows(JTableStudent);

    }//GEN-LAST:event_btngetAllActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
SetValues();
t.Update();
ClearAll();
t.getAllRows(JTableStudent);// TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
if(Tools.Confirm("Are you shur :")){
        SetValues();
t.Delet();
}
ClearAll(); 
t.getAllRows(JTableStudent);// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void JTableStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableStudentMouseClicked
  int roe = JTableStudent.getSelectedRow();
  txtFName.setText(JTableStudent.getValueAt(roe, 0).toString());
    txtSName.setText(JTableStudent.getValueAt(roe,1).toString());
    SimpleDateFormat f =  new SimpleDateFormat("yyyy-MM-dd");
  try{
    Date date = f.parse(JTableStudent.getValueAt(roe, 2).toString());
    txtDate.setDate(date);
  }catch(Exception ex){Tools.MBox(ex.getMessage());}

           txtCity.setText(JTableStudent.getValueAt(roe,3).toString());
               txtStreet.setText(JTableStudent.getValueAt(roe,4).toString());
    txtPostCode.setText(JTableStudent.getValueAt(roe,5).toString());
        txtNati.setText(JTableStudent.getValueAt(roe,6).toString());
    txtNow.setText(JTableStudent.getValueAt(roe,7).toString());
txtold.setText(JTableStudent.getValueAt(roe,8).toString());
txtNumber.setText(JTableStudent.getValueAt(roe,9).toString());
txtEmai.setText(JTableStudent.getValueAt(roe,10).toString());
txtPhone.setText(JTableStudent.getValueAt(roe,11).toString());
txtClassNumber.setText(JTableStudent.getValueAt(roe, 12).toString());
txtClassName.setText(JTableStudent.getValueAt(roe,13).toString());
btnUpdate.setEnabled(true);
btnDelete.setEnabled(true);
btnAdd.setEnabled(false);
 
 
  
    }//GEN-LAST:event_JTableStudentMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
String search = "select * from student_information where ";
if(btnrFName.isSelected()){
search += "FName";
}else if(btnrSName.isSelected()){
search += "SName";
}else if(btnrDate.isSelected()){
search += "BirthDate";
}else if(btnrCity.isSelected()){
search += "City";
}else if(btnrStreet.isSelected()){
search += "Street";
}else if(btnrPostCode.isSelected()){
search += "PostCode";
}else if(btnrNationality.isSelected()){
search += "Nationality";
}else if (btnrNow.isSelected()){
search += "Eduction_Now";
}else if (btnrOld.isSelected()){
search += "Eduction_Old";
}else if (btnrNumber.isSelected()){
search += "Student_Number";
}else if (btnrEmail.isSelected()){
search += "Email";
}else if(btnrPhone.isSelected()){
search += "Phone";
}else if (btnrClassNumber.isSelected()){
search += "Class_Number";
}else if (btnrCalssName.isSelected()){
search += "Class_Name";
}
search += " like '%"+ txtSearch.getText() +"%'" ;
t.getCustomRow(search, JTableStudent);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
this.dispose();
Tools.OpenForm(new frmReport());
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Group;
    private javax.swing.JTable JTableStudent;
    private controls.JButtn btnAdd;
    private controls.JButtn btnBack;
    private controls.JButtn btnBack1;
    private controls.JButtn btnClear;
    private controls.JButtn btnDelete;
    private controls.JButtn btnFind;
    private controls.JButtn btnSearch;
    private controls.JButtn btnUpdate;
    private controls.JButtn btngetAll;
    private javax.swing.JRadioButton btnrCalssName;
    private javax.swing.JRadioButton btnrCity;
    private javax.swing.JRadioButton btnrClassNumber;
    private javax.swing.JRadioButton btnrDate;
    private javax.swing.JRadioButton btnrEmail;
    private javax.swing.JRadioButton btnrFName;
    private javax.swing.JRadioButton btnrNationality;
    private javax.swing.JRadioButton btnrNow;
    private javax.swing.JRadioButton btnrNumber;
    private javax.swing.JRadioButton btnrOld;
    private javax.swing.JRadioButton btnrPhone;
    private javax.swing.JRadioButton btnrPostCode;
    private javax.swing.JRadioButton btnrSName;
    private javax.swing.JRadioButton btnrStreet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtClassName;
    private javax.swing.JTextField txtClassNumber;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtEmai;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtNati;
    private javax.swing.JTextField txtNow;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPostCode;
    private javax.swing.JTextField txtSName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtold;
    // End of variables declaration//GEN-END:variables
}
